default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  strict: true
  pool: 10

development:
  <<: *default
  database: personal_dash_development

test:
  <<: *default
  database: personal_dash_test