default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<: *default
  database: personal_dash_development

test:
  <<: *default
  database: personal_dash_test

production:
  <<: *default
  database: personal_dash_prod
  pool: 25
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASSWORD"]  %>