--- 
user: deploy
group: deploy
pid: /home/deploy/apps/personal_dashboard/shared/tmp/pids/thin.pid
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 1
threaded: true
no-epoll: true
daemonize: true
socket: /home/deploy/apps/personal_dashboard/shared/tmp/sockets/thin.sock
chdir: /home/deploy/apps/personal_dashboard/current
tag: dashing